# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
